### ISSUE TITLE
[Bug]: cannot see editor in page

### ISSUE THREAD

**Issue by darshan-patel-tops** [mohamedsabil83/filament-forms-tinyeditor#99] opened 2023-09-27 09:53 UTC
### What happened?

<?php

namespace App\Filament\Resources;

use App\Filament\Resources\CampusesResource\Pages;
use App\Filament\Resources\CampusesResource\RelationManagers;
use App\Models\Campuses;
use Filament\Forms;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\ToggleColumn;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
// use Mohamedsabil83\FilamentFormsTinyeditor\Components\TinyEditor;
// You have a missing class import. Try importing this class:
use Mohamedsabil83\FilamentFormsTinyeditor\Components\TinyEditor;

class CampusesResource extends Resource
{
    protected static ?string $model = Campuses::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TinyEditor::make('content')->simple(),
                TextInput::make('name234')
            ]);
    }
                                    this is my code and i am trying to use tiny editor here but i cannot see the tab only to use the tiny editor
![Screenshot (82)](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/133767986/685150fd-a841-48f3-8236-995872b3b98c)

### How to reproduce the bug

so i cannot see the editor in my page i don't know what to do
![Screenshot (82)](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/133767986/63aa08fa-7583-4be2-9cb4-79a48c34b75b)
![Screenshot (83)](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/133767986/545e8a99-397a-4d9b-8567-a46667f57e8b)

### Package Version

latest

### PHP Version

802.4

### Laravel Version

10.

### Which operating systems does with happen with?

Windows

**Comment by mohamedsabil83** [comment] 2023-09-27 12:03
In the future, confirm to keep the formation of the issue intact to be clear to read.

Can you check if any issue appears in the browser console?

From your screenshot, it appears you use Filament v2. Then, you'll use v1 of this package. So, force publish the assets. Also, if you published the package's view, force publish it too.

**Comment by jeytii** [comment] 2023-09-27 12:26
@mohamedsabil83 I'm experiencing the same issue. The only error logged is about a missing JS file:
![Screenshot from 2023-09-27 20-19-32](https://github.com/mohamedsabil83/filament-forms-tinyeditor/assets/38130563/a12d9afa-ad38-47b6-9df5-9d49b22349e9)
I tried publishing the config file but still no luck.

Filament: v2
Package: v1.7.0

**Comment by mohamedsabil83** [comment] 2023-09-27 12:41
Update to the latest version, **v1.7.5**, and force publish the package assets.

**Comment by jeytii** [comment] 2023-09-27 14:08
@mohamedsabil83 Still not working :confused:

**Comment by mohamedsabil83** [comment] 2023-09-27 15:59
That's weird. It works as expected on my side. Are you working in Windows, too?
Could you try to create a fresh site and install the package there? There may be something in your current one you forgot about.

**Comment by Darshantada10** [comment] 2023-09-29 15:34
okay so as u said i followed those steps and it is working perfectly fine but as i make the project live on a website it says that No hint path defined for [filament-forms-tinyeditor].

**Comment by shri289** [comment] 2023-09-30 12:38
please, publish the asset by run the following:
`php artisan vendor:publish --tag="filament-forms-tinyeditor-assets"`

Sometimes, you may need to re-publish and override the assets after upgrading:
`php artisan vendor:publish --tag="filament-forms-tinyeditor-assets" --force`

**Comment by markszymik** [comment] 2023-10-03 15:23
Same story. Using it with Forms v2. Page is empty. No console errors etc.
Tried to clear views, config, cache etc.

**Comment by mohamedsabil83** [comment] 2023-10-04 08:59
I can't reproduce the issue. It works as expected. Also, as there are no console errors, there is nothing to achieve. You need to check if you are missing something or if there's a conflict. All that I can say is:
* Please make sure you update all packages.
* If upgraded and have already published assets or views, try to force publish it again.

I have to close the issue for now. If anyone finds the real issue related to this package, don't hesitate to re-open it.

**Closed by mohamedsabil83** 2023-10-04 08:59 UTC
Labels: bug
