### ISSUE TITLE
Cannot focus textarea field in Tinymce modal

### ISSUE THREAD

**Issue by studiowizjo** [mohamedsabil83/filament-forms-tinyeditor#32] opened 2022-09-30 17:18 UTC
Steps to reproduce:

1. Use Tinymce plugins: **code** and/or **codesample**
2. Create form which fires in modal
3. Click in Tinymce on icon to use this option
4. In opened modal, textarea field is not focusable. You cannot select text or edit it.

I believe this is connected with this: https://github.com/tinymce/tinymce/issues/5169 or this: https://github.com/froala/react-froala-wysiwyg/issues/122#issuecomment-916259347 and the solution would be using this code on Tinymce instance:

```
$(document).on('focusin', function(e) {
  if ($(e.target).closest(".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root").length) {
    e.stopImmediatePropagation();
  }
});
```

Unfortunately I couldn`t figure this out.

**Comment by mohamedsabil83** [comment] 2022-10-22 09:04
Can you provide an example code to reproduce the issue?

**Comment by mohamedsabil83** [comment] 2022-10-22 12:53
The reason for that is filament modal use an **AlpineJS** plugin called **focus**. The usage of **x-trap** made this situation.

**Comment by mohamedsabil83** [comment] 2022-10-22 13:44
Fixed in #38. Will be shipped in the next release.

**Closed by mohamedsabil83** 2022-10-22 13:44 UTC

**Comment by studiowizjo** [comment] 2022-10-22 16:42
Perfect, I confirm that works after fix.

You can only remember to remove `console.logs` before release.

**Comment by mohamedsabil83** [comment] 2022-10-22 17:44
Thanks for your confirmation. Also, I already cleared the `console.log`.
